module.exports={
    devServer:{
        open:true,
    },
    configureWebpack:{
        resolve:{
            alias:{
                "com":"@/components",
                "vie":"@/views"
            }
        }
    },
    lintOnSave:false,
}